/**
[ 'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
  'BCDEFGHIJKLMNOPQRSTUVWXYZA',
  'CDEFGHIJKLMNOPQRSTUVWXYZAB',
  'DEFGHIJKLMNOPQRSTUVWXYZABC',
  'EFGHIJKLMNOPQRSTUVWXYZABCD',
  'FGHIJKLMNOPQRSTUVWXYZABCDE',
  'GHIJKLMNOPQRSTUVWXYZABCDEF',
  'HIJKLMNOPQRSTUVWXYZABCDEFG',
  'IJKLMNOPQRSTUVWXYZABCDEFGH',
  'JKLMNOPQRSTUVWXYZABCDEFGHI',
  'KLMNOPQRSTUVWXYZABCDEFGHIJ',
  'LMNOPQRSTUVWXYZABCDEFGHIJK',
  'MNOPQRSTUVWXYZABCDEFGHIJKL',
  'NOPQRSTUVWXYZABCDEFGHIJKLM',
  'OPQRSTUVWXYZABCDEFGHIJKLMN',
  'PQRSTUVWXYZABCDEFGHIJKLMNO',
  'QRSTUVWXYZABCDEFGHIJKLMNOP',
  'RSTUVWXYZABCDEFGHIJKLMNOPQ',
  'STUVWXYZABCDEFGHIJKLMNOPQR',
  'TUVWXYZABCDEFGHIJKLMNOPQRS',
  'UVWXYZABCDEFGHIJKLMNOPQRST',
  'VWXYZABCDEFGHIJKLMNOPQRSTU',
  'WXYZABCDEFGHIJKLMNOPQRSTUV',
  'XYZABCDEFGHIJKLMNOPQRSTUVW',
  'YZABCDEFGHIJKLMNOPQRSTUVWX',
  'ZABCDEFGHIJKLMNOPQRSTUVWXY' ]
 */

// Generate the Tabula Recta matrix
const start = 'A'.charCodeAt(0);
const tabulaRecta = [];

for (let x = 0; x < 26; x += 1) {
  const seq = [];
  for (let y = x; y <= x + 25; y++) {
    const charCode = (y > 25 ? y - 26 : y) + start;

    const char = String.fromCharCode(charCode);
    seq.push(char);
  }
  tabulaRecta.push(seq.join(''));
}

export default tabulaRecta;
